db.tree_things.insert(
    {
        "_id": NumberLong(1),
        "name": "PALLETE01",
        "groupTypeId": 3,
        "groupTypeName": "Facility",
        "groupTypeCode": "",
        "groupId": 3,
        "groupCode": "DF",
        "groupName": "Default Facility",
        "serialNumber": "PALLETE01",
        "rfid":{"_id": NumberLong(2),
            "name": "RFID01",
            "groupTypeId": 3,
            "groupTypeName": "Facility",
            "groupTypeCode": "",
            "groupId": 3,
            "groupCode": "DF",
            "groupName": "Default Facility",
            "serialNumber": "RFID01"
        },
        "carton":{"_id": NumberLong(3),
            "name": "CARTON01",
            "groupTypeId": 3,
            "groupTypeName": "Facility",
            "groupTypeCode": "",
            "groupId": 3,
            "groupCode": "DF",
            "groupName": "Default Facility",
            "serialNumber": "CARTON01",
            "rfid":{
                "_id": NumberLong(4),
                "name": "RFID02",
                "groupTypeId": 3,
                "groupTypeName": "Facility",
                "groupTypeCode": "",
                "groupId": 3,
                "groupCode": "DF",
                "groupName": "Default Facility",
                "serialNumber": "RFID02"
            },
            "box":{"_id": NumberLong(5),
                "name": "BOX01",
                "groupTypeId": 3,
                "groupTypeName": "Facility",
                "groupTypeCode": "",
                "groupId": 3,
                "groupCode": "DF",
                "groupName": "Default Facility",
                "serialNumber": "BOX01",
                "rfid":{"_id": NumberLong(6),
                    "name": "RFID03",
                    "groupTypeId": 3,
                    "groupTypeName": "Facility",
                    "groupTypeCode": "",
                    "groupId": 3,
                    "groupCode": "DF",
                    "groupName": "Default Facility",
                    "serialNumber": "RFID03"
                },
                "item":{"_id": NumberLong(7),
                    "name": "ITEM01",
                    "groupTypeId": 3,
                    "groupTypeName": "Facility",
                    "groupTypeCode": "",
                    "groupId": 3,
                    "groupCode": "DF",
                    "groupName": "Default Facility",
                    "serialNumber": "ITEM01",
                    "rfid":[{"_id": NumberLong(8),
                        "name": "RFID03",
                        "groupTypeId": 3,
                        "groupTypeName": "Facility",
                        "groupTypeCode": "",
                        "groupId": 3,
                        "groupCode": "DF",
                        "groupName": "Default Facility",
                        "serialNumber": "RFID03"
                    },
                        {"_id": NumberLong(9),
                            "name": "RFID04",
                            "groupTypeId": 3,
                            "groupTypeName": "Facility",
                            "groupTypeCode": "",
                            "groupId": 3,
                            "groupCode": "DF",
                            "groupName": "Default Facility",
                            "serialNumber": "RFID04"
                        }
                    ]
                }
            }
        }
    }

)